### ISSUE TITLE
[Bug] Create Custom Profile fails to load

### ISSUE THREAD

**Issue by yoyokenny** [bhopahk/launcher#5]
**Describe the bug**
Fails to load the Create Custom Profile screen.

**To Reproduce**
1. Click on 'Custom Profile'
2. See error

**Operating System:**
Windows 7 x64 Pro

**Launcher Version:**
v0.3.4

**Uploaded Report:**
https://hastebin.com/igiyeruzup.txt

**Notes:**
I have a temporary workaround until the next build. Just unpacked `app.asar`, changed the line to what is in the current source, then repacked `app.asar`

**Comment by bhopahk** [comment]
I fixed this in 193d925fddd788aeb32df78819594ed184950212 but apparently forgot to release a patch. It is fixed in 0.3.5.

Thanks again for the report :)
